package rest

import (
	"github.com/fasthttp/router"
	"github.com/jackc/pgx"
	"github.com/librerialeo/oklever-api/pkg/service"
)

// InitRouterHandler initialize al routes
func InitRouterHandler(r *router.Router, conn *pgx.Conn) {
	s := service.InitService(conn)
	chatsRouter := r.Group("/chats")
	InitChatsHandler(chatsRouter, s)
	ClassesCommentsRouter := r.Group("/classes_comments")
	InitClassesCommentsHandler(ClassesCommentsRouter, s)
	classesRouter := r.Group("/classes")
	InitClassesHandler(classesRouter, s)
	ClassesResourcesRouter := r.Group("/classes_resources")
	InitClassesResourcesHandler(ClassesResourcesRouter, s)
	countriesRouter := r.Group("/countries")
	InitCountriesHandler(countriesRouter, s)
	coursesDatasheetsRouter := r.Group("/courses_datasheets")
	InitCoursesDatasheetsHandler(coursesDatasheetsRouter, s)
	coursesForumsCommentsRouter := r.Group("/courses_forums_comments")
	InitCoursesForumsCommentsHandler(coursesForumsCommentsRouter, s)
	coursesForumsRouter := r.Group("/courses_forums")
	InitCoursesForumsHandler(coursesForumsRouter, s)
	coursesRouter := r.Group("/courses")
	InitCoursesHandler(coursesRouter, s)
	coursesLevelsRouter := r.Group("/courses_levels")
	InitCoursesLevelsHandler(coursesLevelsRouter, s)
	coursesProjectsRouter := r.Group("/courses_projects")
	InitCoursesProjectsHandler(coursesProjectsRouter, s)
	coursesReviewsRouter := r.Group("/courses_reviews")
	InitCoursesReviewsHandler(coursesReviewsRouter, s)
	degreesRouter := r.Group("/degrees")
	InitDegreesHandler(degreesRouter, s)
	insigniasRouter := r.Group("/insignias")
	InitInsigniasHandler(insigniasRouter, s)
	languagesRouter := r.Group("/languages")
	InitLanguagesHandler(languagesRouter, s)
	modulesFeedbackRouter := r.Group("/modules_feedback")
	InitModulesFeedbackHandler(modulesFeedbackRouter, s)
	modulesRouter := r.Group("/modules")
	InitModulesHandler(modulesRouter, s)
	modulesResourcesRouter := r.Group("/modules_resources")
	InitModulesResourcesHandler(modulesResourcesRouter, s)
	purchasesRouter := r.Group("/purchases")
	InitPurchasesHandler(purchasesRouter, s)
	purchasesProductsRouter := r.Group("/purchases_products")
	InitPurchasesProductsHandler(purchasesProductsRouter, s)
	questionsRouter := r.Group("/questions")
	InitQuestionsHandler(questionsRouter, s)
	questionsOptionsRouter := r.Group("/questions_options")
	InitQuestionsOptionsHandler(questionsOptionsRouter, s)
	questionsTypesRouter := r.Group("/questions_types")
	InitQuestionsTypesHandler(questionsTypesRouter, s)
	quizzesRouter := r.Group("/quizzes")
	InitQuizzesHandler(quizzesRouter, s)
	resourcesTypesRouter := r.Group("/resources_types")
	InitResourcesTypesHandler(resourcesTypesRouter, s)
	rolesRouter := r.Group("/roles")
	InitRolesHandler(rolesRouter, s)
	studentsAnswersRouter := r.Group("/students_answers")
	InitStudentsAnswersHandler(studentsAnswersRouter, s)
	studentsCoursesRouter := r.Group("/students_courses")
	InitStudentsCoursesHandler(studentsCoursesRouter, s)
	studentsRouter := r.Group("/students")
	InitStudentsHandler(studentsRouter, s)
	studentsProjectsRouter := r.Group("/students_projects")
	InitStudentsProjectsHandler(studentsProjectsRouter, s)
	studentsProjectsHistoryRouter := r.Group("/students_projects_history")
	InitStudentsProjectsHistoryHandler(studentsProjectsHistoryRouter, s)
	studentsQuizzesRouter := r.Group("/students_quizzes")
	InitStudentsQuizzesHandler(studentsQuizzesRouter, s)
	studentsSubscriptionsRouter := r.Group("/students_subscriptions")
	InitStudentsSubscriptionsHandler(studentsSubscriptionsRouter, s)
	subscriptionsRouter := r.Group("/subscriptions")
	InitSubscriptionsHandler(subscriptionsRouter, s)
	synchronousClassesRouter := r.Group("/synchronous_classes")
	InitSynchronousClassesHandler(synchronousClassesRouter, s)
	synchronousClassesResourcesRouter := r.Group("/synchronous_classes_resources")
	InitSynchronousClassesResourcesHandler(synchronousClassesResourcesRouter, s)
	teachersExpertisesRouter := r.Group("/teachers_expertises")
	InitTeachersExpertisesHandler(teachersExpertisesRouter, s)
	teachersRouter := r.Group("/teachers")
	InitTeachersHandler(teachersRouter, s)
	teachersLanguagesRouter := r.Group("/teachers_languages")
	InitTeachersLanguagesHandler(teachersLanguagesRouter, s)
	teachersManagementsRouter := r.Group("/teachers_managements")
	InitTeachersManagementsHandler(teachersManagementsRouter, s)
	teachersResearchRouter := r.Group("/teachers_research")
	InitTeachersResearchHandler(teachersResearchRouter, s)
	teachersTeachingRouter := r.Group("/teachers_teaching")
	InitTeachersTeachingHandler(teachersTeachingRouter, s)
	teachersTeachingInstitutionsRouter := r.Group("/teachers_teaching_institutions")
	InitTeachersTeachingInstitutionsHandler(teachersTeachingInstitutionsRouter, s)
	teachersTeachingSignaturesRouter := r.Group("/teachers_teaching_signatures")
	InitTeachersTeachingSignaturesHandler(teachersTeachingSignaturesRouter, s)
	testClassesFeedbackRouter := r.Group("/test_classes_feedback")
	InitTestClassesFeedbackHandler(testClassesFeedbackRouter, s)
	testClassesRouter := r.Group("/test_classes")
	InitTestClassesHandler(testClassesRouter, s)
	topicsRouter := r.Group("/topics")
	InitTopicsHandler(topicsRouter, s)
	topicsResourcesRouter := r.Group("/topics_resources")
	InitTopicsResourcesHandler(topicsResourcesRouter, s)
	usersChatsRouter := r.Group("/users_chats")
	InitUsersChatsHandler(usersChatsRouter, s)
	usersDegreesRouter := r.Group("/users_degrees")
	InitUsersDegreesHandler(usersDegreesRouter, s)
	usersRouter := r.Group("/users")
	InitUsersHandler(usersRouter, s)
	usersInsigniasRouter := r.Group("/users_insignias")
	InitUsersInsigniasHandler(usersInsigniasRouter, s)
}
